
name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the blu_spark-10 branch
  push:
    branches: [ blu_spark-10 ]
  pull_request:
    branches: [ blu_spark-10 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Apt Update
        run: |
          cd ${HOME}
          export GCC="gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu"
          wget "https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/${GCC}.tar.xz"
          xz -d ${GCC}.tar.xz
          tar xvf ${GCC}.tar
          rm -rf ${GCC}.tar
          export ARCH="arm64"
          export PATH="${HOME}/${GCC}/bin:$PATH"
          export CROSS_COMPILE="aarch64-none-linux-gnu-"
          echo $ARCH
          echo $PATH
